FROM python:3.10-slim

WORKDIR /app

COPY ./app /app

ENV PYTHONPATH=/app

RUN pip install --no-cache-dir -r /app/requirements.txt

# Optional: nur wenn du statisch was mitliefern willst
COPY trivy_output.json /app/trivy_output.json

CMD ["python", "main.py"]
