FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

# Optional: nur wenn du statisch was mitliefern willst
COPY trivy_output.json /app/trivy_output.json

CMD ["python", "main.py"]
