name: Docker Image Scan & DeepSeek Reporting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Pull Docker image
      run: docker pull ghcr.io/enesaslnts/matchdaybot:latest

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@v0.13.1
      with:
        image-ref: ghcr.io/enesaslnts/matchdaybot:latest
        format: table
        exit-code: 0
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'
